markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

site_name: Root Cause Systems
site_url: https://rootcausesystems.com
repo_url: https://github.com/RootCauseSystems/website

theme:
  name: material
  logo: assets/logo-RCS.png
  favicon: assets/logo-RCS.png
  palette:
    scheme: slate
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

# This must be all the way to the left!
extra_css:
  - stylesheets/cyberpunk.css

plugins:
  - search
  - blog:
      blog_dir: journal
      authors_file: journal/.authors.yml  # Note the removal of {blog}/

nav:
  - Root Cause Systems: index.md
  - Tools: tools/auditor.md
  - Journal: journal/index.md